export default function () {
  return {
    pokemons: [
      { id: 1, name: "Bulbasaur", types: [5, 6] },
      { id: 2, name: "Ivysaur", types: [5, 6] },
      { id: 3, name: "Venusaur", types: [5, 6] },
      { id: 4, name: "Charmender", types: [1] },
      { id: 5, name: "Charmeleon", types: [1] },
      { id: 6, name: "Charizard", types: [1, 4] },
      { id: 7, name: "Squirtle", types: [3] },
      { id: 8, name: "Wartotle", types: [3] },
      { id: 9, name: "Blastoise", types: [3] },
      { id: 10, name: "Caterpie", types: [12] },
      { id: 11, name: "Metapod", types: [12] },
      { id: 12, name: "Buterfree", types: [12,4] },
    ],
    types: [
      { name: "Normal", color: "" },
      { name: "Fire", color: "red" },
      { name: "Fighting", color: "" },
      { name: "Water", color: "blue" },
      { name: "Flying", color: "indigo-10" },
      { name: "Grass", color: "green" },
      { name: "Poison", color: "purple" },
      { name: "Electric", color: "" },
      { name: "Ground", color: "" },
      { name: "Psychic", color: "" },
      { name: "Rock", color: "" },
      { name: "Ice", color: "" },
      { name: "Bug", color: "lime-7" },
      { name: "Dragon", color: "" },
      { name: "Ghost", color: "" },
      { name: "Dark", color: "" },
      { name: "Steel", color: "" },
      { name: "Fairy", color: "" },
      { name: "???", color: "" },
    ],
  }
}
